// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    Cache: require('./libs/Cache'),
    MemoryCache: require('./libs/MemoryCache'),
    FileCache: require('./libs/FileCache'),
    RedisCache: require('./libs/RedisCache')
  };

}).call(this);

//# sourceMappingURL=index.js.map
