// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, cache;

  cache = require('memory-cache');

  Promise = require('bluebird');

  module.exports = function() {
    return {
      set: function(key, value, expired) {
        if (expired != null) {
          cache.put(key, value, expired);
        } else {
          cache.put(key, value);
        }
        return Promise.resolve;
      },
      get: function(key) {
        return Promise["try"](function() {
          return cache.get(key);
        });
      }
    };
  };

}).call(this);

//# sourceMappingURL=MemoryCache.js.map
